export const ROUTES = [
  '/',

  '/home',
  // '/community',
  '/team',
  '/dovercon',
  '/conference',
  '/cfp',
  '/sponsoring',
  // '/posts',
  '/copyright',
  '/privacy',
  '/contribution-guidelines',

  '/ctf',
  '/ctf/about',
  '/ctf/2021/spring',
  '/ctf/2021/autumn',
  '/ctf/2022/spring',

  '/conference/2021/about',
  '/conference/2021/cfp',
  '/conference/2021/mentors',
  '/conference/2021/speakers',
  '/conference/2021/schedule',
  '/conference/2021/sponsoring',
  '/conference/2021/team',
  '/conference/2021/code-of-conduct',

  '/conference/2022/about',
  '/conference/2022/cfp',
  '/conference/2022/mentors',
  '/conference/2022/speakers',
  '/conference/2022/schedule',
  '/conference/2022/sponsoring',
  '/conference/2022/team',
  '/conference/2022/code-of-conduct',

  '/404-not-found',

  '/discord',
  '/youtube',
  '/watch',
  '/music-playlist',
  '/afterparty',
  '/cfpform',

  /*
  '/tags',
  '/tags/Community',
  '/tags/Convention',
  '/tags/Cryptocurrency',
  '/tags/Cryptography',
  '/tags/CTF',
  '/tags/Cyber%20Security',
  '/tags/Development',
  '/tags/External%20Content',
  '/tags/Information%20Security',
  '/tags/IOT',
  '/tags/Media',
  '/tags/Mobile',
  '/tags/OSINT',
  '/tags/Personal',
  '/tags/Privacy',
  '/tags/Programming',
  '/tags/Talks',
  '/tags/Web',

  '/authors/AtomicNicos',
  '/authors/Mrs.%20Skelli',
  '/authors/Night',

  '/post/2021/2021_02_06+Hello-World',*/
];
