export const ROUTES = [
  '/',

  '/home',
  '/community',
  '/team',
  '/dovercon',
  '/posts',
  '/copyright',
  '/privacy',
  '/contribution-guidelines',

  '/ctf',
  '/ctf/2021-01',

  '/dovercon/2021/about',
  '/dovercon/2021/cfp',
  '/dovercon/2021/mentors',
  '/dovercon/2021/speakers',
  '/dovercon/2021/schedule',
  '/dovercon/2021/sponsoring',
  '/dovercon/2021/team',
  '/dovercon/2021/code-of-conduct',

  '/404-not-found',

  '/discord',
  '/youtube',
  '/music-playlist',
  '/afterparty',

  '/tags',
  '/tags/Community',
  '/tags/Convention',
  '/tags/Cryptocurrency',
  '/tags/Cryptography',
  '/tags/CTF',
  '/tags/Cyber%20Security',
  '/tags/Development',
  '/tags/External%20Content',
  '/tags/Information%20Security',
  '/tags/IOT',
  '/tags/Media',
  '/tags/Mobile',
  '/tags/OSINT',
  '/tags/Personal',
  '/tags/Privacy',
  '/tags/Programming',
  '/tags/Talks',
  '/tags/Web',

  '/authors/AtomicNicos',
  '/authors/Mrs.%20Skelli',
  '/authors/Night',

  '/post/2021/2021_02_06+Hello-World',
];
